version: 2

models:
  - name: customers
    description: this is the customers output table
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_customers
    description: this is the stg_customers table
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id